services:
  db:
    image: postgres:17-alpine
    container_name: wsports_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: wsports_tracker_saas_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: wsports_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/wsports_tracker_saas_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: wsports_frontend
    restart: always
    ports:
      - "8080:80" # Sol taraf senin tarayıcın (Windows), sağ taraf Nginx portu (Docker içi)
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000 # Eğer Vue projesinde Vite kullanıyorsan API adresini belirtmek için

volumes:
  postgres_data:
