# docker-compose.yml
version: '3.8'

services:
  api:
    build: ./backend
    container_name: wsports_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - wsports_network

  db:
    image: postgres:15-alpine
    container_name: wsports_tracker_saas_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 # Canlıda .env'den alınmalıdır
      POSTGRES_DB: wsports_tracker_saas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wsports_network

networks:
  wsports_network:
    driver: bridge

volumes:
  postgres_data: